// src/styles/AmbassadorDrawer.styles.js
import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

export const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 99999,
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 17, 34, 0.65)',
    ...Platform.select({
      web: {
        backdropFilter: 'blur(12px)',
      }
    }),
  },

  /* Desktop: slide-in from right */
  drawer: {
    maxWidth: '75%', 
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.navy,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: { width: -8, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
    elevation: 20,
  },

  /* Mobile: bottom-sheet */
  mobileDrawer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.navy,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
    elevation: 20,
    overflow: 'hidden',
  },

  /* Drag handle */
  dragHandleArea: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 8,
    cursor: 'grab',
  },
  dragHandleBar: {
    width: 48,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.textMuted,
  },

  formContainer: {
    flex: 2.2,
    backgroundColor: COLORS.navy,
  },
  scrollForm: {
    padding: 40,
    gap: 24,
  },
  headerBadges: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badgeEvent: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.textDark,
    fontSize: 12,
    fontWeight: '400',
    lineHeight: '124%',
    backgroundColor: '#A3AFAE',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
  },
  headerInsignia: {
    width: 64,
    height: 64,
    resizeMode: 'contain',
  },
  headerLine: {
    height: 1.5,
    backgroundColor: '#A3AFAE',
    marginTop: -24,
  },
  mainTitle: {
    maxWidth: 495,
    fontFamily: FONTS.serif,
    fontSize: 32,
    color: COLORS.white,
    fontWeight: '600',
    lineHeight: '125%',
    marginBottom: 10,
  },
  instructionsHeading: {
    fontFamily: FONTS.sansSerif,
    fontSize: 15,
    color: COLORS.textLight,
    fontWeight: '500',
    marginBottom: 8,
  },
  stepsRow: {
    flexDirection: 'row',
    gap: 16,
  },
  stepCard: {
    flex: 1,
    backgroundColor: '#113E5E',
    borderRadius: 6,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    borderWidth: 1.5,
    borderColor: '#2C2C35',
  },
  stepNum: {
    fontFamily: FONTS.numbers,
    fontSize: 48,
    fontWeight: '700',
    color: COLORS.gold,
    lineHeight: '125%',
    marginTop: -4,
    ...Platform.select({
      web: {
        backgroundImage: 'linear-gradient(180deg, #CABB91 0%, #BA9842 100%)',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
      }
    }),
  },
  stepText: {
    flex: 1,
    fontFamily: FONTS.sansSerif,
    fontSize: 14,
    lineHeight: '145%',
    color: COLORS.textLight,
  },
  limitSubtext: {
    fontFamily: FONTS.sansSerif,
    color: '#4E6578',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: '124%',
    marginTop: -8,
    marginBottom: 24,
  },
  formGrid: {
    gap: 24,
  },
  formRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  fieldBlock: {
    flex: 1,
    minWidth: 150,
    gap: 8,
  },
  fieldLabel: {
    maxWidth: 320,
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    lineHeight: '125%',
    color: COLORS.textLight,
    fontWeight: '400',
  },
  input: {
    fontFamily: FONTS.sansSerif,
    backgroundColor: COLORS.darkNavy,
    borderWidth: 1.5,
    borderColor: '#2C2C35',
    borderRadius: 6,
    height: 48,
    paddingHorizontal: 16,
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '124%',
  },
  inputError: {
    borderColor: COLORS.redAccent,
  },
  errorText: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.redAccent,
    fontSize: 14,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: '124%',
  },
  addPersonBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: COLORS.gold,
    borderRadius: 6,
    paddingVertical: 14,
    marginTop: 16,
    backgroundColor: 'rgba(197, 160, 89, 0.05)',
    gap: 8,
  },
  addPersonBtnPlus: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.gold,
    fontWeight: '500',
    fontSize: 20,
    lineHeight: '124%',
    marginTop: -2,
  },
  addPersonBtnText: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.gold,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: '124%',
    letterSpacing: 0.5,
  },
  formFooter: {
    marginLeft: '20%',
    marginTop: '3%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 30,
    flexWrap: 'wrap',
  },
  mobileFormFooter: {
    marginLeft: 0,
    marginTop: 24,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 16,
  },
  agreementText: {
    marginLeft: '15%',
    maxWidth: 400,
    flex: 1,
    fontFamily: FONTS.sansSerif,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: '124%',
    color: '#4E6578',
    fontStyle: 'italic',
  },
  mobileAgreementText: {
    marginLeft: 0,
    maxWidth: '100%',
    flex: undefined,
    textAlign: 'center',
    fontStyle: 'italic',

  },
  policyLink: {
    textDecorationLine: 'underline',
    color: '#4E6578',
    fontStyle: 'italic',

  },
  submitBtn: {
    marginRight: '10%',
    backgroundColor: '#EEEEEE',
    paddingVertical: 14,
    paddingHorizontal: 68,
    borderRadius: 4,
  },
  mobileSubmitBtn: {
    marginRight: 0,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  submitBtnText: {
    color: COLORS.navy,
    fontFamily: FONTS.sansSerif,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: '124%',
    letterSpacing: 0.5,
  },

  /* Aligned Success View Styles */
  successBlock: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: '100%',
  },
  successCenteredContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
    width: '100%',
  },
  successTitle: {
    fontFamily: FONTS.serif,
    fontSize: 48,
    color: COLORS.white,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: "105%",
    maxWidth: 663,
    marginTop: 20,
  },
  successText: {
    color: '#8E8E93',
    fontSize: 18,
    fontWeight: '400',
    lineHeight: '145%',
    textAlign: 'center',
    maxWidth: 583,
    marginBottom: 64,
  },
  successHomeBtn: {
    backgroundColor: '#EEEEEE',
    paddingVertical: 14,
    paddingHorizontal: 54,
    borderRadius: 4,
    marginTop: 10,
  },
  successHomeBtnText: {
    color: COLORS.darkNavy,
    fontFamily: FONTS.sansSerif,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: '124%',
    letterSpacing: 0.5,
  },
  successFooter: {
    flex: 0.05,
    width: '100%',
    height: '6%',
    paddingBottom: 0,
    backgroundColor: '#012138',
    borderTopWidth: 1,
    borderColor: '#456D89',
    paddingTop: '2%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  successFooterLabel: {
    fontFamily: FONTS.sansSerif,
    color: '#4E6578',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: '125%',
  },
  successFooterLink: {
    fontFamily: FONTS.sansSerif,
    color: '#265D82',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '125%',
  },
  successFooterSeparator: {
    color: '#153A54',
    fontSize: 16,
  },

  /* Arbitru Sidebar Styles (desktop only) */
  arbitruSidebar: {
    flex: 1,
    maxWidth: 360,
    borderLeftWidth: 1.5,
    borderLeftColor: COLORS.gold,
    position: 'relative',
  },
  sidebarBg: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  sidebarTintOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 17, 34, 0.7)',
  },
  sidebarGradientOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
    ...Platform.select({
      web: {
        backgroundImage: 'linear-gradient(0deg, #002448 0%, rgba(0, 36, 72, 0) 50%)',
      },
      default: {
        backgroundColor: 'rgba(0, 36, 72, 0.4)',
      }
    })
  },

  /* Confirmation Modal Styles */
  confirmOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 999999,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  confirmBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 17, 34, 0.75)',
    ...Platform.select({
      web: {
        backdropFilter: 'blur(12px)',
        WebkitBackdropFilter: 'blur(12px)',
      },
    }),
  },
  confirmModalBox: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: '#01213B',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 8,
    paddingVertical: 32,
    paddingHorizontal: 28,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 25,
    zIndex: 1000000,
  },
  confirmIconWrapper: {
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmTitle: {
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    lineHeight: '140%',
    fontWeight: '400',
    color: COLORS.white,
    textAlign: 'center',
    marginBottom: 28,
  },
  confirmActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    gap: 16,
  },
  confirmNoBtn: {
    flex: 1,
    height: 48,
    borderWidth: 1,
    borderColor: COLORS.white,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  confirmNoBtnText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.white,
    letterSpacing: 0.5,
  },
  confirmYesBtn: {
    flex: 1,
    height: 48,
    backgroundColor: COLORS.white,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  confirmYesBtnText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '600',
    color: '#01213B',
    letterSpacing: 0.5,
  },
});
