// src/styles/Costs.styles.js
import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

export const styles = StyleSheet.create({
  sectionContainer: {
    backgroundColor: COLORS.lightBg,
    paddingHorizontal: '6%',
    ...Platform.select({
      web: {
        backgroundImage: `url(${require('../../assets/images/grainy-background.svg')})`,
        backgroundRepeat: 'repeat',
      }
    }),
  },
  leftColumn: {
    minWidth: 285,
    maxWidth: 365,
    borderRightWidth: 2,
    borderRightColor: '#A3AFAE',
    paddingRight: 24,
    paddingBottom: 60,
  },
  stickyWrapper: {
    position: 'sticky',
    top: 80,
    paddingTop: 80,
  },
  sidebarFirstWord: {
    fontFamily: FONTS.serif,
    fontSize: 32,
    fontWeight: '700',
    color: '#000000',
  },
  sidebarSecondWord: {
    fontFamily: FONTS.serif,
    fontSize: 32,
    fontWeight: '700',
    color: '#8E8E93',
    marginTop: 4,
  },
  mainColumn: {
    flex: 1,
    width: '100%',
    paddingVertical: 60,
  },

  /* Mobile Sticky Title (replaces left column on mobile) */
  mobileStickyTitleWrapper: {
    marginRight: '-6.5%',
    position: 'sticky',
    top: 0,
    backgroundColor: COLORS.lightBg,
    paddingVertical: 16,
    marginBottom: 8,
    zIndex: 100,
    borderBottomWidth: 1,
    borderBottomColor: '#A3AFAE',
    marginLeft: -20,
    paddingLeft: 20,
    ...Platform.select({
      web: {
        backgroundImage: `url(${require('../../assets/images/grainy-background.svg')})`,
        backgroundRepeat: 'repeat',
      }
    }),
  },
  mobileStickyTitleFirst: {
    fontFamily: FONTS.serif,
    fontSize: 28,
    fontWeight: '700',
    color: '#000000',
    lineHeight: '125%',
  },
  mobileStickyTitleSecond: {
    fontFamily: FONTS.serif,
    fontSize: 28,
    fontWeight: '700',
    color: '#8E8E93',
    marginTop: 2,
    lineHeight: '125%',
  },

  /* Section and Grid Layouts */
  sectionBlock: {
    width: '100%',
    maxWidth: '80%',
    marginBottom: 60,
    gap: 20,
  },
  tagRowContainer: {
    width: '100%',
    position: 'relative',
    height: 32,
    justifyContent: 'flex-end',
    marginBottom: 16,
  },
  tagWrapper: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    backgroundColor: '#A3AFAE',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    zIndex: 2,
    overflow: 'hidden',
  },
  tagText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textDark,
    lineHeight: '124%',
    textTransform: 'uppercase',
  },
  tagSeparatorLine: {
    height: 1.5,
    backgroundColor: '#A3AFAE',
    width: '100%',
    position: 'absolute',
    left: 0,
    bottom: 0,
    zIndex: 1,
  },
  gridRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 24,
  },
  gridLeft: {
    width: 200,
    marginRight: 200,
  },
  gridRight: {
    flex: 1,
    width: 300,
  },
  rowDivider: {
    height: 1,
    backgroundColor: '#A3AFAE',
    width: '100%',
    marginVertical: 4,
  },

  /* Price and Text Typography */
  priceBig: {
    fontFamily: FONTS.numbers,
    fontSize: 58,
    // marginright: '5%',
    fontWeight: '700',
    lineHeight: '100%',
    color: COLORS.textDark,
    // gap: 36,
  },
  priceUnit: {
    marginLeft: '15%',
    minWidth: 100,
    fontSize: 16,
    color: COLORS.textMuted,
    fontWeight: '400',
    lineHeight: '150%',
  },
  descTitle: {
    fontFamily:  FONTS.sansSerif,
    fontSize: 24,
    fontWeight: '400',
    color: COLORS.textDark,
    lineHeight: '145%',
  },
  descDetail: {
    fontSize: 24,
    color: COLORS.textDark,
    fontWeight: '400',
    lineHeight: '145%',
    marginTop: 4,
  },
  noteLabel: {
    fontFamily: FONTS.serif,
    fontSize: 24,
    color: COLORS.textMuted,
    fontWeight: '600',
    lineHeight: '100%',
  },
  noteText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '400',
    color: COLORS.textMuted,
    lineHeight: '145%', 
  },

  /* Action Buttons & Badges */
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: 8,
  },
  registerBtn: {
    height: 48,
    minWidth: 205,
    backgroundColor: COLORS.navy,
    // paddingVertical: 10,
    paddingHorizontal: 18,
    marginLeft: 420,
    borderRadius: 4,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  registerBtnText: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.white,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: '124%',
    letterSpacing: 0.5,
  },
  registerIcon: {
    width: 18,
    height: 18,
    resizeMode: 'contain',
  },
  placesLeftText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '125%',
    color: COLORS.textMuted,
    fontStyle: 'italic',
  },

  /* Image Carousel */
  carouselContainer: {
    position: 'relative',
    width: 'auto',
    marginRight: '-400px',
    marginVertical: 24,
  },
  carouselScroll: {
    gap: 16,
    paddingRight: 100,
  },
  carouselImage: {
    width: 386,
    height: 255,
    flexShrink: 0,
    aspectRatio: 386 / 255,
    borderRadius: 4,
    resizeMode: 'cover',
  },
  carouselPlaceholderImage: {
    width: 386,
    height: 255,
    flexShrink: 0,
    aspectRatio: 386 / 255,
    borderRadius: 4,
    backgroundColor: '#CFD6D9',
    borderWidth: 1,
    borderColor: '#A3AFAE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  carouselArrow: {
    position: 'absolute',
    top: '50%',
    marginTop: -20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    zIndex: 20,
  },
  arrowLeft: {
    left: -20,
  },
  arrowRight: {
    left: 768,
  },

  /* Inner Links */
  linkWrapper: {
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  linkLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textDark,
    textDecorationLine: 'underline',
  },
  linkArrow: {
    width: 14,
    height: 14,
    marginLeft: 8,
  },

  /* Mobile Costs styles */
  mobileSectionContainer: {
    backgroundColor: COLORS.lightBg,
    paddingHorizontal: '6%',
    paddingBottom: 60,
    width: '100%',
    ...Platform.select({
      web: {
        backgroundImage: `url(${require('../../assets/images/grainy-background.svg')})`,
        backgroundRepeat: 'repeat',
      }
    }),
  },
  mobileSectionBlock: {
    width: '100%',
    marginBottom: 48,
    gap: 16,
  },
  mobilePriceBig: {
    fontFamily: FONTS.numbers,
    fontSize: 58,
    fontWeight: '700',
    lineHeight: '100%',
    color: COLORS.textDark,
  },
  mobilePriceUnit: {
    fontSize: 16,
    color: COLORS.textMuted,
    fontWeight: '400',
    marginLeft: 8,
  },
  mobileDescTitle: {
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    fontWeight: '500',
    color: COLORS.textDark,
    lineHeight: '145%',
  },
  mobileDescDetail: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    color: COLORS.textMuted,
    lineHeight: '145%',
    marginTop: 4,
  },
  mobileRowDivider: {
    height: 1.5,
    backgroundColor: '#A3AFAE',
    width: '100%',
    marginVertical: 8,
  },
  mobileNoteLabel: {
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    fontWeight: '500',
    color: COLORS.textMuted,
  },
  mobileNoteText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    color: COLORS.textMuted,
    lineHeight: '145%',
  },
  mobileActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: 16,
    flexWrap: 'wrap',
  },
  mobileRegisterBtn: {
    backgroundColor: COLORS.navy,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  mobileRegisterBtnText: {
    color: COLORS.white,
    fontFamily: FONTS.sansSerif,
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 0.5,
  },
  mobileRegisterIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
  },
  mobilePlacesLeftText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 15,
    color: COLORS.textDark,
    fontStyle: 'italic',
  },
  mobileTagRowContainer: {
    width: '100%',
    position: 'relative',
    height: 32,
    justifyContent: 'flex-end',
    marginBottom: 8,
  },
  mobileTagWrapper: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    backgroundColor: '#A3AFAE',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    zIndex: 2,
  },
  mobileTagText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textDark,
    lineHeight: '124%',
    textTransform: 'uppercase',
  },
  mobileTagSeparatorLine: {
    height: 1.5,
    backgroundColor: '#A3AFAE',
    width: '100%',
    position: 'absolute',
    left: 0,
    bottom: 0,
    zIndex: 1,
  },
  mobileCarouselContainer: {
    width: 'auto',
    position: 'relative',
    marginVertical: 16,
    marginRight: '-7%',
    overflow: 'hidden',
  },
  mobileCarouselScroll: {
    gap: 16,
    paddingRight: 24,
  },
  mobileCarouselImage: {
    width: 280,
    height: 180,
    flexShrink: 0,
    aspectRatio: 280 / 180,
    borderRadius: 6,
    resizeMode: 'cover',
  },
  mobileCarouselPlaceholderImage: {
    width: 280,
    height: 180,
    backgroundColor: '#E5E7EB',
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileCarouselArrow: {
    position: 'absolute',
    top: '50%',
    marginTop: -22,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  mobileArrowLeft: {
    left: 12,
  },
  mobileArrowRight: {
    right: 12,
  },
  mobileLinkWrapper: {
    marginTop: 8,
  },
  mobileLinkLabel: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.textDark,
    textDecorationLine: 'underline',
  },
  mobileLinkArrow: {
    width: 14,
    height: 14,
    marginLeft: 6,
    resizeMode: 'contain',
  },
  mobileInnerContainer: {
    paddingLeft: 20,
    width: '100%',
  },
  mobileVerticalBorder: {
    position: 'absolute',
    left: '6%',
    top: 0,
    bottom: 0,
    width: 1.5,
    backgroundColor: '#A3AFAE',
    zIndex: 200,
  },
});
