 // frontend/src/styles/CourseDetails.styles.js
import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

export const styles = StyleSheet.create({
  /* Desktop: container style */
  sectionContainer: {
    backgroundColor: COLORS.lightBg,
    position: 'relative',
    width: '100%',
  },
  stickyViewport: {
    // Removed position: 'sticky', top: 0, and height: '100vh' to allow natural page flow
    width: '100%',
    paddingLeft: '6%',
    overflow: 'visible',
  },
  leftColumn: {
    minWidth: 285,
    maxWidth: 365,
    borderRightWidth: 2,
    borderRightColor: COLORS.gold,
    paddingRight: 24,
  },
  mainColumn: {
    flex: 1,
    maxWidth: 1086,
    paddingVertical: 60,
    justifyContent: 'center',
    gap: 40,
  },
  sectionTitle: {
    fontFamily: FONTS.serif,
    fontSize: 48,
    color: '#091413',
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: '125%',
  },
  cardStackWrapper: {
    position: 'relative',
    width: '100%',
  },
  card: {
    position: 'absolute',
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: COLORS.lightBg,
    paddingTop: 32,
    gap: 30,
    borderTopWidth: 1.5,
    borderTopColor: COLORS.gold,
  },
  cardWithBorder: {},
  itemNumber: {
    lineHeight: '125%',
    fontFamily: FONTS.numbers,
    fontSize: 84,
    color: COLORS.gold,
    fontWeight: '700',
    fontStyle: 'normal',
    marginTop: -10,
    width: 80,
    ...Platform.select({
      web: {
        backgroundImage: 'linear-gradient(180deg, #CABB91 0%, #BA9842 100%)',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
      }
    }),
  },
  itemText: {
    flex: 1,
    fontFamily: FONTS.sansSerif,
    fontSize: 26,
    color: '#091413',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '145%',
  },

  /* Mobile: natural flow, no animation */
  mobileSectionContainer: {
    backgroundColor: COLORS.lightBg,
    paddingHorizontal: '6%',
    paddingVertical: 48,
    position: 'relative',
  },
  mobileVerticalBorder: {
    position: 'absolute',
    left: '6%',
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: COLORS.gold,
    zIndex: 10,
  },
  mobileInnerContainer: {
    paddingLeft: 16,
    width: '100%',
  },
  mobileSectionTitle: {
    fontFamily: FONTS.serif,
    marginTop: 0,
    fontSize: 24,
    fontWeight: 600,
    lineHeight: '125%',
  },
  mobileCardStack: {
    flexDirection: 'column',
    width: 'auto',
    marginLeft: -16,
    marginRight: 0,
    gap: 0,
  },
  mobileCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: COLORS.lightBg,
    paddingTop: 24,
    paddingBottom: 24,
    paddingLeft: 16,
    paddingRight: 0,
    gap: 16,
    borderTopWidth: 1.5,
    borderTopColor: '#E5CCA9',
  },
  mobileItemNumber: {
    fontFamily: FONTS.numbers,
    fontSize: 28,
    color: COLORS.gold,
    fontWeight: '700',
    lineHeight: '115%',
    marginTop: -4,
    width: 36,
    flexShrink: 0,
    ...Platform.select({
      web: {
        backgroundImage: 'linear-gradient(180deg, #CABB91 0%, #BA9842 100%)',
        backgroundClip: 'text',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
      }
    }),
  },
  mobileItemText: {
    flex: 1,
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    color: '#091413',
    fontWeight: '400',
    lineHeight: '145%',
  },

  /* Event Card */
  eventCard: {
    width: '100%',
    maxWidth: '100%',
    backgroundColor: '#BAC2C5',
    borderRadius: 4,
    overflow: 'hidden',
    position: 'relative',
    minHeight: 200,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  grainyOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    ...Platform.select({
      web: {
        backgroundImage: `url(${require('../../assets/images/grainy-background.svg')})`,
        backgroundRepeat: 'repeat',
        opacity: 0.12,
        pointerEvents: 'none',
      }
    })
  },
  imageBackgroundContainer: {
    position: 'absolute',
    top: 60,
    right: 0,
    bottom: 0,
    width: '40%',
    height: '80%',
    zIndex: 1,
    overflow: 'hidden',
  },
  fadeGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    ...Platform.select({
      web: {
        backgroundImage: 'linear-gradient(90deg, #BAC2C5 0%, rgba(186, 194, 197, 0.4) 40%, rgba(186, 194, 197, 0) 100%)',
      }
    })
  },
  eventDetails: {
    padding: 32,
    gap: 16,
    justifyContent: 'center',
  },
  tagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  tagDivider: {
    height: 1,
    backgroundColor: 'rgba(9, 20, 19, 0.15)',
    width: '200%',
    // marginTop: 16,
  },
  tagGold: {
    backgroundColor: '#A3AFAE',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderTopRightRadius: 4,
    borderTopLeftRadius: 4,
  },
  tagGoldText: {
    color: COLORS.textDark,
    fontFamily: FONTS.sansSerif,
    fontSize: 12,
    textAlign: 'center',
    lineHeight: '124%',
    fontWeight: '400',
    letterSpacing: 0.5,
  },
  placesLeftText: {
    color: COLORS.textMuted,
    fontFamily: FONTS.sansSerif,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: '125%',
  },
  eventTitle: {
    fontFamily: FONTS.serif,
    fontSize: 26,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  eventLocation: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    color: COLORS.textMuted,
    fontWeight: '400',
    lineHeight: '125%',
    marginTop: -10,
  },
  eventBtn: {
    backgroundColor: COLORS.navy,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  eventBtnText: {
    color: COLORS.white,
    fontFamily: FONTS.sansSerif,
    fontWeight: '500',
    lineHeight: '124%',
    fontSize: 14,
    letterSpacing: 0.5,
  },
  eventBtnIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
  },
  eventCardImage: {
    position: 'absolute',
    width: '101.538%',
    height: '119.543%',
    left: -6,
    top: -43.017,
    transform: [{ scaleX: -1 }],
  },

  /* Mobile Event Card styles */
  mobileEventCard: {
    backgroundColor: '#BAC2C5',
    borderRadius: 4,
    overflow: 'hidden',
    position: 'relative',
    minHeight: 200,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  mobileGrainyOverlay: {
    display: 'none',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    ...Platform.select({
      web: {
        backgroundImage: `url(${require('../../assets/images/grainy-background.svg')})`,
        backgroundRepeat: 'repeat',
        opacity: 0.12,
        pointerEvents: 'none',
      }
    })
  },
  mobileImageBackgroundContainer: {
    display: 'none',
    position: 'absolute',
    top: 60,
    right: 0,
    bottom: 0,
    width: '40%',
    height: '80%',
    zIndex: 1,
    overflow: 'hidden',
  },
  mobileEventCardImage: {
    position: 'absolute',
    width: '101.538%',
    height: '119.543%',
    left: -6,
    top: -43.017,
    transform: [{ scaleX: -1 }],
  },
  mobileFadeGradient: {
    display: 'none',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    ...Platform.select({
      web: {
        backgroundImage: 'linear-gradient(90deg, #BAC2C5 0%, rgba(186, 194, 197, 0.4) 40%, rgba(186, 194, 197, 0) 100%)',
      }
    })
  },
  mobileEventDetails: {
    padding: 32,
    gap: 16,
    justifyContent: 'center',
  },
  mobileTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  mobileTagDivider: {
    height: 1,
    backgroundColor: 'rgba(9, 20, 19, 0.15)',
    width: '100%',
  },
  mobileTagGold: {
    backgroundColor: '#A3AFAE',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderTopRightRadius: 4,
    borderTopLeftRadius: 4,
  },
  mobileTagGoldText: {
    color: COLORS.textDark,
    fontFamily: FONTS.sansSerif,
    fontSize: 12,
    textAlign: 'center',
    lineHeight: '124%',
    fontWeight: '400',
    letterSpacing: 0.5,
  },
  mobilePlacesLeftText: {
    // flex: 'column',
    marginLeft: '30%',
    color: COLORS.textMuted,
    fontFamily: FONTS.sansSerif,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: '125%',
  },
  mobileEventTitle: {
    fontFamily: FONTS.serif,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '600',
    color: COLORS.textDark,
  },
  mobileEventLocation: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    color: COLORS.textMuted,
    fontWeight: '400',
    lineHeight: '125%',
    marginTop: -10,
  },
  mobileEventBtn: {
    width: 293,
    backgroundColor: COLORS.navy,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    alignSelf: 'flex-start',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  mobileEventBtnText: {
    color: COLORS.white,
    fontFamily: FONTS.sansSerif,
    fontWeight: '500',
    lineHeight: '124%',
    fontSize: 14,
    letterSpacing: 0.5,
  },
  mobileEventBtnIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
  },
});