// src/styles/Footer.styles.js
import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

export const styles = StyleSheet.create({
  footerContainer: { 
    backgroundColor: COLORS.navy, 
    paddingBottom: 24, 
    position: 'relative',
    justifyContent: 'space-between',
    width: '100%',
  },

  /* Ambassador Top V-Flap Section */
  ambassadorSection: {
    width: '100%',
    height: '52%',
    position: 'relative',
    alignItems: 'center',
    overflow: 'visible',
    marginBottom: 40,
  },
  svgAbsoluteContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: -80, // Extended downwards to allow the deeper gold V-flap tip to project lower
    zIndex: 1,
  },
  ambassadorContent: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
    marginTop: '3%',
  },
  ambassadorTitle: { 
    fontFamily: FONTS.serif, 
    marginTop: '-6%',
    fontSize: 64, 
    fontWeight: '600', 
    color: COLORS.textDark,
    lineHeight: '125%',
    textAlign: 'center',
  },
  ambassadorSubtitle: {
    marginTop: '1%',
    marginBottom: 36,
    fontFamily: FONTS.sansSerif, 
    fontSize: 24, 
    color: COLORS.textDark, 
    fontWeight: '400',
    lineHeight: '145%',
    textAlign: 'center',
  },
  ambassadorBtn: { 
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.navy, 
    paddingVertical: 18, 
    paddingHorizontal: 32, 
    borderRadius: 4, 
    marginTop: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
  },
  ambassadorBtnText: { 
    fontFamily: FONTS.sansSerif,
    color: COLORS.white, 
    fontWeight: '500', 
    fontSize: 16,
    lineHeight: '124%', 
    letterSpacing: 0.5,
  },
  dvcLogoInside: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
    marginTop: 81,
    zIndex: 10,
  },

  /* Middle Columns Content Wrapper */
  lowerContentArea: {
    marginTop: '-10%',
    width: '100%',
    paddingHorizontal: '8%',
    zIndex: 5,
  },
  logoStack: {
    marginTop: '-5%',
    paddingBottom: '5%',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
    marginBottom: 20,
  },
  mainSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 32,
    zIndex: 5,
  },
  columnContacts: {
    flex: 1,
    minWidth: 200,
  },
  columnLinks: {
    marginRight: '10%',
    marginLeft: '-20%',
    flex: 1,
    minWidth: 200,
  },
  columnLocation: {
    flex: 1, 
    minWidth: 280,
  },

  /* Column specific styles */
  footerLogo: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
  },
  footerLogoMisia: {
    width: 100,
    height: 48,
    resizeMode: 'contain',
  },
  colTitleContacts: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.lightGold,
    marginBottom: 14,
  },
  contactTextGold: {
    fontFamily: FONTS.sansSerif,
    fontSize: 15,
    color: COLORS.gold,
    marginBottom: 8,
    fontWeight: '500',
  },
  colTitle: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.lightGold,
    marginBottom: 14,
  },
  linkItem: {
    alignSelf: 'flex-start',
  },
  linkTextGold: {
    fontFamily: FONTS.sansSerif,
    fontSize: 15,
    color: COLORS.gold,
    marginBottom: 8,
    fontWeight: '500',
  },
  linkTextGoldHover: {
    color: COLORS.lightGold,
  },
  colTitleLocation: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.lightGold,
    marginBottom: 14,
  },
  mapContainer: {
    maxWidth: '507px',
    height: '140',
    borderRadius: 8,
    overflow: 'hidden',
  },

  /* Bottom Metadata Bar */
  bottomBar: { 
    borderTopWidth: 1, 
    borderTopColor: '#456D89', 
    paddingTop: 18, 
    flexDirection: 'row', 
    flexWrap: 'wrap', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    gap: 24,
    zIndex: 5,
    paddingHorizontal: '8%',
  },
  legalLinksGroup: { 
    flexDirection: 'row', 
    flexWrap: 'wrap', 
    alignItems: 'center', 
    gap: 12 
  },
  legalLabel: { 
    color: '#456D89', 
    fontSize: 16, 
    fontWeight: '500',
    lineHeight: '125%',
    marginRight: 4,
  },
  legalLink: { 
    color: '#113E5E', 
    fontSize: 16, 
    fontWeight: '400',
    lineHeight: '125%',
  },
  legalSeparator: { 
    color: '#113E5E', 
    fontSize: 16, 
    fontWeight: '400',
    lineHeight: '145%',
    marginHorizontal: 2 
  },
  copyright: { 
    color: '#113E5E', 
    fontSize: 16, 
    fontWeight: '500',
    lineHeight: '125%',
    display: 'none', 
  },
  mobileFooterContainer: {
    backgroundColor: COLORS.navy,
    paddingBottom: 24,
    position: 'relative',
    justifyContent: 'space-between',
    width: '100%',
  },
  mobileAmbassadorSection: {
    width: '100%',
    height: 380,
    position: 'relative',
    alignItems: 'center',
    overflow: 'visible',
    marginBottom: 40,
  },
  mobileSvgAbsoluteContainer: {
    width: '250%',
    marginLeft: '-75%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: -80,
    zIndex: 1,
  },
  mobileAmbassadorContent: {
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
    marginTop: '3%',
  },
  mobileAmbassadorTitle: {
    fontFamily: FONTS.serif,
    marginTop: '6%',
    fontSize: 28,
    fontWeight: '600',
    color: COLORS.textDark,
    lineHeight: '125%',
    textAlign: 'center',
  },
  mobileAmbassadorSubtitle: {
    width: 243,
    marginTop: '1%',
    marginBottom: 36,
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    color: COLORS.textDark,
    fontWeight: '400',
    lineHeight: '145%',
    textAlign: 'center',
  },
  mobileAmbassadorBtn: {
    height: 48,
    minWidth: 205,
    // maxWidth: 242,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.navy,
    // paddingVertical: 18,
    paddingHorizontal: 18,
    borderRadius: 4,
    marginTop: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    // alignSelf: 'stretch',
    alignItems: 'center',
    justifyContent: 'center',
  },
  mobileAmbassadorBtnText: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.white,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: '124%',
    letterSpacing: 0.5,
  },
  mobileDvcLogoInside: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
    marginTop: 54,
    zIndex: 10,
  },
  mobileLowerContentArea: {
    marginTop: '-10%',
    width: '100%',
    paddingHorizontal: '8%',
    zIndex: 5,
  },
  mobileLogoStack: {
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: 12,
  },
  mobileContactsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 24,
  },
  mobileMainSection: {
    justifyContent: 'space-between',
    gap: 32,
    zIndex: 5,
  },
  mobileColumnContacts: {
    flex: 1,
    minWidth: 150,
  },
  mobileColumnLinks: {
    flex: 1,
    minWidth: 200,
  },
  mobileColumnLocation: {
    flex: 1,
    minWidth: 280,
  },
  mobileFooterLogo: {
    width: 60,
    height: 60,
    resizeMode: 'contain',
  },
  mobileFooterLogoMisia: {
    width: 100,
    height: 48,
    resizeMode: 'contain',
  },
  mobileColTitleContacts: {
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    lineHeight: '145%',
    fontWeight: '500',
    color: COLORS.lightGold,
    marginBottom: 14,
  },
  mobileContactTextGold: {
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    lineHeight: '145%',
    fontWeight: '400',
    color: COLORS.gold,
    marginBottom: 8,
    fontWeight: '500',
  },
  mobileColTitle: {
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    lineHeight: '145%',
    fontWeight: '500',
    color: COLORS.lightGold,
    marginBottom: 14,
  },
  mobileLinkTextGold: {
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    lineHeight: '145%',
    fontWeight: '400',
    color: COLORS.gold,
    marginBottom: 8,
  },
  mobileLinkTextGoldHover: {
    color: COLORS.lightGold,
  },
  mobileColTitleLocation: {
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    lineHeight: '145%',
    fontWeight: '500',
    color: COLORS.lightGold,
    marginBottom: 14,
  },
  mobileMapContainer: {
    maxWidth: '507px',
    height: '140',
    borderRadius: 8,
    overflow: 'hidden',
  },
  mobileBottomBar: {
    borderTopWidth: 1,
    borderTopColor: '#456D89',
    paddingTop: 18,
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
    zIndex: 5,
    paddingHorizontal: '8%',
    marginTop: 24,
    // paddingBottom: 28,
  },
  mobileLegalLinksGroup: {
    paddingTop: 24,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 12,
  },
  mobileLegalLabel: {
    paddingTop: 28,

    color: '#456D89',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: '125%',
    marginBottom: 4,
  },
  mobileLegalLink: {
    color: '#113E5E',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '125%',
  },
  mobileLegalSeparator: {
    color: '#113E5E',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '145%',
    marginHorizontal: 4,
  },
  mobileCopyright: {
    display: 'none',
    color: '#7998AF',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: '125%',
    marginTop: 16,
  },
});