// src/styles/Header.styles.js
import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

export const styles = StyleSheet.create({
  headerContainer: {
    height: 80,
    backgroundColor: COLORS.navyNavbar,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '6%',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDark,
    zIndex: 9999,
    elevation: 10,
  },
  logoGroup: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  headerLogo: { width: 45, height: 45, resizeMode: 'contain' },
  navLinks: { flexDirection: 'row', gap: 16, alignItems: 'center' },
  homeBtn: {
    padding: 10,
    borderRadius: 4,  
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  homeIcon: {
    lineHeight: '124%',
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  navItemBtn: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 4,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navItemActiveBtn: {
    backgroundColor: COLORS.darkNavy,
  },
  navItemText: {
    color: COLORS.textLight,
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    lineHeight: '124%',
    fontWeight: '500',
    letterSpacing: 1,
  },
  registerBtn: {
    backgroundColor: COLORS.white,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.gold,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  registerBtnText: {
    color: '#091413',
    fontFamily: FONTS.sansSerif,
    fontWeight: '500',
    fontStyle: 'normal',
    lineHeight: '124%',
    textTransform: 'uppercase',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  registerIcon: { width: 16, height: 16, resizeMode: 'contain' },

  /* Mobile Hamburger */
  hamburgerBtn: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  hamburgerLine: {
    width: 24,
    height: 2,
    backgroundColor: COLORS.textLight,
    borderRadius: 2,
  },

  /* Mobile Slide-Down Menu */
  mobileMenu: {
    position: 'absolute',
    top: 80,
    left: 0,
    right: 0,
    backgroundColor: COLORS.navyNavbar,
    zIndex: 9998,
    overflow: 'auto',
    elevation: 20,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.gold,
    paddingBottom: 16,
  },
  mobileNavItem: {
    paddingVertical: 18,
    paddingHorizontal: '6%',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderDark,
    backgroundColor: 'transparent',
  },
  mobileNavItemText: {
    color: COLORS.textLight,
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    fontWeight: '500',
    letterSpacing: 1.5,
    lineHeight: '124%',
  },
  mobileMenuRegisterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: '6%',
    paddingVertical: 20,
    marginTop: 12,
    gap: 20,
  },
  mobileRegisterBtn: {
    backgroundColor: COLORS.white,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.gold,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mobileMenuPlaces: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.white,
    fontFamily: FONTS.sansSerif,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: '125%',
  },
});
