// src/styles/Instructors.styles.js
import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

export const styles = StyleSheet.create({
  // ─── Desktop layout ───────────────────────────────────────────────────────
  innerContainer: {
    maxWidth: 1086,
    gap: 16,
    width: '100%',
  },
  sectionTitle: {
    fontFamily: FONTS.serif,
    fontSize: 48,
    lineHeight: '125%',
    fontWeight: '600',
    color: COLORS.textDark,
    marginBottom:  64,
  },
  instructorRow: {
    gap: 16,
  },
  instructorHeader: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.gold,
    paddingBottom: 20,
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 16,
    marginBottom: 8,
  },
  nameBadgeGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
  },
  instructorName: {
    fontFamily: FONTS.sansSerif,
    fontSize: 24,
    fontWeight: '400',
    lineHeight: '145%',
    color: COLORS.textDark,
  },
  badge: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
  },
  badgeText: {
    fontSize: 13,
    color: COLORS.textMuted,
    fontWeight: '400',
    lineHeight: '125%',
  },
  logosGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  logoMisia: {
    width: 50,
    height: 35,
    resizeMode: 'contain',
  },
  logoIroa: {
    width: 45,
    height: 35,
    resizeMode: 'contain',
  },
  contentCard: {
    marginTop: -24,
    position: 'relative',
    backgroundColor: '#EEEEEE',
    borderBottomRightRadius: 8,
    minHeight: 180,
    overflow: 'hidden',
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageContainer1: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    width: 'calc(55% + 8px)',
  },
  imageContainer2: {
    position: 'absolute',
    top: 0,
    left: 'calc(45% - 8px)',
    bottom: 0,
    width: 'calc(55% + 8px)',
  },
  instructorImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    filter: 'grayscale(100%)',
  },
  instructorImage2: {
    width: '100%',
    height: '100%',
    paddingTop: '50%',
    resizeMode: 'cover',
    filter: 'grayscale(100%)',
  },
  mirroredImage: {
    transform: [{ scaleX: -1 }],
  },
  fadeOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
    pointerEvents: 'none',
    backgroundColor: 'transparent',
    backgroundImage: 'linear-gradient(90deg, #EEEEEE 20%, rgba(238, 238, 238, 0) 65%)',
  },
  textContent: {
    zIndex: 10,
    padding: 24,
    justifyContent: 'center',
  },
  descriptionText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 15,
    lineHeight: 24,
    color: COLORS.textMuted,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.gold,
    marginLeft: '-4%',
    width: '104%',
  },

  // ─── Mobile layout ────────────────────────────────────────────────────────
  mobileSectionTitle: {
    fontFamily: FONTS.serif,
    fontSize: 32,
    lineHeight: '125%',
    fontWeight: '600',
    color: COLORS.textDark,
    marginBottom: 10,
  },
  mobileOuterContainer: {
    position: 'relative',
    paddingHorizontal: '6%',
    width: '100%',
  },
  mobileVerticalBorder: {
    position: 'absolute',
    left: '6%',
    top: -32,
    bottom: -32,
    width: 2,
    backgroundColor: COLORS.gold,
    zIndex: 10,
  },
  mobileInnerContainer: {
    paddingLeft: 16,
  },
  mobileInstructorBlock: {
    marginBottom: 32,
  },
  mobileImageWrapper: {
    width: '100%',
    height: 220,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    marginBottom: 16,
    marginRight: '-6%',
  },
  mobileInstructorImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    filter: 'grayscale(100%)',
  },
  mobileImageBottomFade: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 70,
    pointerEvents: 'none',
    backgroundImage: 'linear-gradient(180deg, rgba(244, 245, 247, 0) 0%, #F4F5F7 100%)',
  },
  mobileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  mobileBadgeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  mobileGoldLine: {
    height: 1,
    backgroundColor: COLORS.gold,
    marginBottom: 16,
    marginRight: '-6%',
  },
  mobileDescriptionText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 15,
    lineHeight: 24,
    color: COLORS.textMuted,
    fontWeight: '400',
  },
});
