// frontend/src/styles/Opportunities.styles.js
import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

export const styles = StyleSheet.create({
  sectionContainer: {
    backgroundColor: COLORS.white,
    paddingHorizontal: '6%',
  },
  leftColumn: {
    minWidth: 285,
    maxWidth: 365,
    borderRightWidth: 2,
    borderRightColor: COLORS.gold,
    paddingRight: 24,
  },
  mainColumn: {
    flex: 1,
    width: '100%',
    paddingVertical: 80,
    gap: 32,
  },
  title: {
    fontFamily: FONTS.serif,
    fontSize: 42,
    color: COLORS.textDark,
    fontWeight: '600',
    lineHeight: '125%',
  },
  opportunitiesGrid: {
    flexDirection: 'column',
    width: '100%',
    gap: 16,
    marginTop: 10,
  },

  /* Row Containers */
  rowContainer: {
    width: '109%',
    minHeight: 110,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#8E8E93',
    overflow: 'hidden',
    backgroundColor: '#CDD7D6',
  },
  rowLeftBox: {
    width: 100,
    backgroundColor: '#9CAFAE',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    borderColor: '#8E8E93',
  },
  rowRightContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },

  /* Inline Branding Logo Measures */
  ipscShieldLogo: {
    width: 65,
    height: 65,
    resizeMode: 'contain',
  },
  iroaLeftLogo: {
    width: 80,
    height: 55,
    resizeMode: 'contain',
  },
  misiaLeftLogo: {
    width: 80,
    height: 55,
    resizeMode: 'contain',
  },
  frameLeftLogo: {
    width: 48,
    height: 48,
    resizeMode: 'contain',
  },

  /* Right Column Typography */
  badgeTextLink: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '24px',
    color: COLORS.textDark,
    textDecorationLine: 'underline',
  },
  badgeTextArrow: {
    width: 18,
    height: 18,
    marginLeft: 12,
  },
  pathwayTextLabel: {
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '24px',
    color: COLORS.textDark,
    marginRight: 8,
  },
  buttonGroupRow: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  pathwayBtn: {
    backgroundColor: '#00254B',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: 'transparent',
  },
  pathwayBtnActive: {
    borderColor: COLORS.gold,
  },
  pathwayBtnText: {
    color: '#FFFFFF',
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '500',
    lineHeight: '124%',
  },

  /* Descriptive Text Blocks */
  description: {
    fontFamily: FONTS.sansSerif,
    fontSize: 24,
    lineHeight: '145%',
    fontWeight: '400',
    color: COLORS.textDark,
    maxWidth: 1118,
    paddingTop: '1%',
    paddingBottom: '3%',
  },

  /* Custom Double-Quote Blocks */
  quoteBlock: {
    maxWidth: 1142,
    height: 380,
    backgroundColor: COLORS.navy,
    borderRadius: 4,
    padding: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    marginTop: 16,
    width: '100%',
  },
  quoteInnerBorder: {
    height: '100%',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 4,
    overflow: 'hidden',
    flexDirection: 'row',
  },
  quoteLeftCol: {
    flex: 3,
    minWidth: 280,
    padding: 32,
    gap: 20,
    borderRightColor: COLORS.border,
    borderBottomColor: COLORS.border,
    position: 'relative',
  },
  quoteTextItalic: {
    fontFamily: FONTS.serif,
    fontSize: 18,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: '145%',
    color: COLORS.textLight,
  },
  quoteRightCol: {
    flex: 1.1,
    minWidth: 150,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  oppLogo: {
    width: 110,
    height: 110,
    resizeMode: 'contain',
  },

  /* Mobile Quote Extras */
  mobileQuoteLogoTop: {
    alignItems: 'center',
    paddingTop: 24,
    paddingBottom: 8,
  },
  mobileOppLogo: {
    width: 80,
    height: 80,
    resizeMode: 'contain',
  },
  mobileClosingQuotes: {
    alignSelf: 'flex-end',
    marginTop: 8,
  },
  /* Mobile Opportunities styles */
  mobileSectionContainer: {
    backgroundColor: COLORS.white,
    paddingHorizontal: '6%',
    paddingVertical: 48,
    width: '100%',
    position: 'relative',
  },
  mobileVerticalBorder: {
    position: 'absolute',
    left: '6%',
    top: 0,
    bottom: 0,
    width: 2,
    backgroundColor: COLORS.gold,
    zIndex: 10,
  },
  mobileInnerContainer: {
    paddingLeft: 16,
    width: '100%',
  },
  mobileTitle: {
    fontFamily: FONTS.serif,
    fontSize: 32,
    color: COLORS.textDark,
    fontWeight: '600',
    lineHeight: '125%',
    marginBottom: 20,
  },
  mobileOpportunitiesGrid: {
    flexDirection: 'column',
    width: '100%',
    gap: 16,
    marginBottom: 24,
  },
  mobileCard1Container: {
    position: 'relative',
    width: 'auto',
    height: 185,
    marginRight: '-8%',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderLeftWidth: 1.5,
    borderTopWidth: 1.5,
    borderBottomWidth: 1.5,
    borderRightWidth: 0,
    borderColor: '#8E8E93',
    overflow: 'hidden',
    backgroundColor: '#CDD7D6',
  },
  mobileCard1BottomImage: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    width: '100%',
    height: '52%',
    zIndex: 1,
  },
  mobileCard1BottomImageNative: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    width: '100%',
    height: '52%',
    resizeMode: 'cover',
    zIndex: 1,
  },
  mobileCard2Container: {
    position: 'relative',
    width: 'auto',
    height: 185,
    marginRight: '-8%',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    borderLeftWidth: 1.5,
    borderTopWidth: 1.5,
    borderBottomWidth: 1.5,
    borderRightWidth: 0,
    borderColor: '#8E8E93',
    overflow: 'hidden',
    backgroundColor: '#CDD7D6',
  },
  mobileLogoGreyWatermark: {
    position: 'absolute',
    right: 45,
    top: '50%',
    transform: [{ translateY: '-50%' }],
    width: 64,
    height: 64,
    resizeMode: 'contain',
    opacity: 0.8,
    pointerEvents: 'none',
  },
  logoGreyWatermark: {
    position: 'absolute',
    right: 40,
    top: '50%',
    transform: [{ translateY: '-50%' }],
    width: 110,
    height: 110,
    resizeMode: 'contain',
    opacity: 0.8,
    pointerEvents: 'none',
  },
  mobileCardContent: {
    padding: 16,
    flexDirection: 'column',
    justifyContent: 'space-between',
    flex: 1,
  },
  mobileCard1Header: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
    zIndex: 2,
    position: 'relative',
  },
  mobileCard2Header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  mobileIpscShieldLogo: {
    width: 44,
    height: 44,
    resizeMode: 'contain',
  },
  mobileIroaHeaderLogo: {
    width: 56,
    height: 38,
    resizeMode: 'contain',
  },
  mobileMisiaHeaderLogo: {
    width: 56,
    height: 38,
    resizeMode: 'contain',
  },
  mobileFrameHeaderLogo: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
  },
  frameLeftLogo: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
  },
  mobileBadgeTextLink: {
    fontFamily: FONTS.sansSerif,
    fontSize: 15,
    fontWeight: '500',
    lineHeight: '20px',
    color: COLORS.textDark,
    textDecorationLine: 'underline',
    flex: 1,
  },
  mobileBadgeTextArrow: {
    width: 16,
    height: 16,
    marginLeft: 8,
  },
  mobilePathwayTextLabel: {
    fontFamily: FONTS.sansSerif,
    fontSize: 15,
    fontWeight: '400',
    lineHeight: '20px',
    color: COLORS.textDark,
  },
  mobileButtonGroupColumn: {
    flexDirection: 'column',
    gap: 8,
    alignItems: 'flex-start',
    width: 160,
  },
  mobilePathwayBtn: {
    backgroundColor: '#01223C',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 4,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  mobilePathwayBtnActive: {
    backgroundColor: '#001A30',
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  mobilePathwayBtnText: {
    color: '#FFFFFF',
    fontFamily: FONTS.sansSerif,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: '124%',
  },
  mobileDescription: {
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    lineHeight: '145%',
    fontWeight: '400',
    color: COLORS.textDark,
    marginVertical: 16,
  },
  mobileQuoteBlock: {
    height: 475,
    backgroundColor: COLORS.navy,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 0,
    marginTop: 16,
    marginRight: '-8%',
    width: 'auto',
  },
  mobileQuoteInnerBorder: {
    height: '100%',
    borderWidth: 1,
    borderRightWidth: 0,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  mobileQuoteContent: {
    flex: 1,
    justifyContent: 'center',
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 20,
    paddingRight: 24,
    gap: 12,
  },
  mobileQuoteTextItalic: {
    fontFamily: FONTS.serif,
    fontSize: 16,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: '145%',
    color: COLORS.textLight,
  },
});
