// src/styles/RegisterDrawer.styles.js
import { StyleSheet, Platform } from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

export const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 99999,
  },
  backdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 17, 34, 0.65)',
    ...Platform.select({
      web: {
        backdropFilter: 'blur(12px)',
      }
    }),
  },

  /* Desktop: slide-in from right */
  drawer: {
    maxWidth: '75%',
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.navy,
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: { width: -8, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
    elevation: 20,
  },

  /* Mobile: bottom-sheet slide up */
  mobileDrawer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.navy,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.35,
    shadowRadius: 15,
    elevation: 20,
    overflow: 'hidden',
  },

  /* Drag handle at top of mobile drawer */
  dragHandleArea: {
    width: '100%',
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 8,
    cursor: 'grab',
  },
  dragHandleBar: {
    width: 48,
    height: 4,
    borderRadius: 2,
    backgroundColor: COLORS.textMuted,
  },

  formContainer: {
    flex: 2.2,
    backgroundColor: COLORS.navy,
  },
  scrollForm: {
    padding: 40,
    gap: 24,
  },
  headerBadges: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  badgeEvent: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.textDark,
    fontSize: 12,
    fontWeight: '400',
    lineHeight: '124%',
    backgroundColor: '#A3AFAE',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
  },
  badgeSeats: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.textLight,
    fontSize: 18,
    fontWeight: '400',
    lineHeight: '125%',
  },
  headerLine: {
    height: 1.5,
    backgroundColor: '#A3AFAE',
    marginTop: -24,
  },
  mainTitle: {
    maxWidth: '50%',
    fontFamily: FONTS.serif,
    fontSize: 32,
    color: COLORS.white,
    fontWeight: '600',
    lineHeight: '125%',
    marginBottom: 20,
  },
  formGrid: {
    gap: 24,
  },
  formRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 20,
  },
  fieldBlock: {
    flex: 1,
    minWidth: 150,
    gap: 8,
  },
  fieldLabel: {
    maxWidth: 320,
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    lineHeight: '125%',
    color: COLORS.textLight,
    fontWeight: '400',
    minHeight: 42,
  },
  input: {
    fontFamily: FONTS.sansSerif,
    backgroundColor: COLORS.darkNavy,
    borderWidth: 1.5,
    borderColor: '#2C2C35',
    borderRadius: 6,
    height: 48,
    paddingHorizontal: 16,
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '124%',
  },
  inputError: {
    borderColor: COLORS.redAccent,
  },
  errorText: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.redAccent,
    fontSize: 14,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: '124%',
  },
  spinnerContainer: {
    maxWidth: 110,
    backgroundColor: COLORS.darkNavy,
    borderWidth: 1.5,
    borderColor: '#2C2C35',
    borderRadius: 6,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: 16,
    overflow: 'hidden',
  },
  spinnerInput: {
    color: COLORS.white,
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '124%',
    flex: 1,
    minWidth: 0,
    height: '100%',
    paddingHorizontal: 4,
    ...Platform.select({
      web: {
        outlineStyle: 'none',
      },
    }),
  },
  spinnerValue: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '124%',
  },
  spinnerArrows: {
    width: 40,
    height: '100%',
    borderLeftWidth: 1.5,
    borderLeftColor: '#2C2C35',
    backgroundColor: '#001A33',
  },
  arrowBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 0.5,
    borderBottomColor: '#2C2C35',
  },
  arrowText: {
    color: '#8E8E93',
    fontSize: 9,
  },
  helpText: {
    fontFamily: FONTS.sansSerif,
    color: '#4E6578',
    fontSize: 14,
    fontWeight: '400',
    fontStyle: 'italic',
    lineHeight: '124%',
    paddingBottom: 54,
  },
  dropdownTrigger: {
    maxWidth: 320,
    backgroundColor: COLORS.darkNavy,
    borderWidth: 1.5,
    borderColor: '#2C2C35',
    borderRadius: 6,
    height: 48,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  dropdownTriggerError: {
    borderColor: COLORS.redAccent,
  },
  dropdownTriggerText: {
    fontFamily: FONTS.sansSerif,
    fontWeight: '400',
    lineHeight: '124%',
    color: COLORS.white,
    fontSize: 16,
  },
  dropdownArrow: {
    color: '#4E6578',
    fontSize: 10,
  },
  dropdownMenu: {
    maxWidth: 320,
    position: 'absolute',
    top: 76,
    left: 0,
    right: 0,
    backgroundColor: '#001122',
    borderWidth: 1.5,
    borderColor: '#2C2C35',
    borderRadius: 6,
    overflow: 'hidden',
  },
  dropdownItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2C35',
  },
  dropdownItemHovered: {
    backgroundColor: '#CDD7D6',
  },
  dropdownItemText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '124%',
  },
  dropdownItemTextHovered: {
    color: COLORS.textDark,
  },
  selectorContainer: {
    // marginTop: '-24px',
    maxWidth: 320,
    flexDirection: 'column',
    gap: 16,
    marginTop: 4,
  },
  selectorOption: {
    // marginTop: '-24px',
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1.5,
    borderColor: '#2C2C35',
    borderRadius: 6,
    paddingVertical: 14,
    paddingHorizontal: 20,
    backgroundColor: 'transparent',
  },
  selectorOptionSelected: {
    backgroundColor: '#1E4E75',
    borderColor: COLORS.gold,
  },
  selectorOptionError: {
    borderColor: COLORS.gold,
  },
  selectorOptionText: {
    fontFamily: FONTS.sansSerif,
    color: '#4E6578',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '124%',
  },
  selectorOptionTextSelected: {
    color: COLORS.white,
  },
  radioCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#4E6578',
  },
  radioCircleSelected: {
    borderColor: COLORS.white,
    backgroundColor: COLORS.white,
  },
  mandatoryError: {
    color: COLORS.gold,
    fontSize: 14,
    fontStyle: 'italic',
    fontWeight: '400',
    lineHeight: '124%',
    marginTop: 4,
  },
  accomHelpText: {
    fontFamily: FONTS.sansSerif,
    fontWeight: '400',
    lineHeight: '124%',
    color: '#8E8E93',
    fontSize: 12,
    fontStyle: 'italic',
    marginTop: 4,
  },
  formFooter: {
    marginLeft: '20%',
    marginTop: '10%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 30,
    flexWrap: 'wrap',
  },
  /* Mobile form footer: stacked vertically */
  mobileFormFooter: {
    marginLeft: 0,
    marginTop: 24,
    flexDirection: 'column',
    alignItems: 'stretch',
    gap: 16,
  },
  agreementText: {
    marginLeft: '15%',
    maxWidth: 450,
    flex: 1,
    fontFamily: FONTS.sansSerif,
    fontSize: 14,
    fontWeight: '400',
    lineHeight: '124%',
    color: '#4E6578',
    fontStyle: 'italic',
  },
  mobileAgreementText: {
    marginLeft: 0,
    maxWidth: '100%',
    flex: undefined,
    textAlign: 'center',
    fontStyle: 'italic',

  },
  policyLink: {
    textDecorationLine: 'underline',
    color: '#4E6578',
  },
  submitBtn: {
    marginRight: '10%',
    backgroundColor: '#EEEEEE',
    paddingVertical: 14,
    paddingHorizontal: 68,
    borderRadius: 4,
  },
  /* Mobile: full-width submit button */
  mobileSubmitBtn: {
    marginRight: 0,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  submitBtnText: {
    color: COLORS.navy,
    fontFamily: FONTS.sansSerif,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: '124%',
    letterSpacing: 0.5,
  },

  /* Success View Styles */
  successBlock: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: '100%',
  },
  successCenteredContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
    width: '100%',
  },
  successTitle: {
    fontFamily: FONTS.serif,
    fontSize: 48,
    color: COLORS.white,
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: "105%",
    maxWidth: 663,
    marginTop: 20,
  },
  successText: {
    color: '#8E8E93',
    fontSize: 18,
    fontWeight: '400',
    lineHeight: '145%',
    textAlign: 'center',
    maxWidth: 583,
    marginBottom: 64,
  },
  successHomeBtn: {
    backgroundColor: '#EEEEEE',
    paddingVertical: 14,
    paddingHorizontal: 54,
    borderRadius: 4,
    marginTop: 10,
  },
  successHomeBtnText: {
    color: COLORS.darkNavy,
    fontFamily: FONTS.sansSerif,
    fontWeight: '500',
    fontSize: 16,
    lineHeight: '124%',
    letterSpacing: 0.5,
  },
  successFooter: {
    flex: 0.05,
    width: '100%',
    height: '6%',
    paddingBottom: 0,
    backgroundColor: '#012138',
    borderTopWidth: 1,
    borderColor: '#456D89',
    paddingTop: '2%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  successFooterLabel: {
    fontFamily: FONTS.sansSerif,
    color: '#4E6578',
    fontSize: 16,
    fontWeight: '500',
    lineHeight: '125%',
  },
  successFooterLink: {
    fontFamily: FONTS.sansSerif,
    color: '#265D82',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '125%',
  },
  successFooterSeparator: {
    color: '#153A54',
    fontSize: 16,
  },

  /* Instructors Sidebar Styles (desktop only) */
  instructorsSidebar: {
    maxWidth: 360,
    flex: 1,
    borderLeftWidth: 1.5,
    borderLeftColor: COLORS.gold,
  },
  sidebarProfile: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
    justifyContent: 'flex-end',
  },
  profileBg: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  profileBgMatvei: {
    ...StyleSheet.absoluteFillObject,
    width: '120%',
    height: '120%',
    resizeMode: 'cover',
    transform: [
      { scale: 1.7 },
      { translateX: -100 },
      { translateY: 10 },
    ],
    ...Platform.select({
      web: {
        filter: 'grayscale(100%)',
      },
      default: {}
    })
  },
  mirroredImage: {
    transform: [{ scaleX: -1 }],
  },
  profileTintOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 17, 34, 0.7)',
  },
  profileGradientOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
    ...Platform.select({
      web: {
        backgroundImage: 'linear-gradient(0deg, #002448 0%, rgba(0, 36, 72, 0) 50%)',
      },
      default: {
        backgroundColor: 'rgba(0, 36, 72, 0.4)',
      }
    })
  },
  profileDetailsContent: {
    zIndex: 10,
    padding: 24,
    gap: 12,
  },
  profileHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  profileName: {
    fontFamily: FONTS.serif,
    fontSize: 24,
    lineHeight: '105%',
    fontWeight: '600',
    color: COLORS.white,
  },
  profileMisia: {
    width: 44,
    height: 28,
    resizeMode: 'contain',
  },
  profileIroa: {
    width: 40,
    height: 28,
    resizeMode: 'contain',
  },
  profileBadgesGroup: {
    flexDirection: 'row',
    gap: 8,
  },
  miniBadge: {
    marginTop: "-1%",
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    borderRadius: 100,
    paddingVertical: 4,
    paddingHorizontal: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  miniBadgeText: {
    fontFamily: FONTS.sansSerif,
    color: COLORS.white,
    fontSize: 16,
    lineHeight: '125%',
    fontWeight: '400',
  },
  profileDesc: {
    color: COLORS.white,
    fontFamily: FONTS.sansSerif,
    fontSize: 16,
    fontWeight: '400',
    lineHeight: '145%',
  },
});
