// src/styles/RegisterBanner.styles.js
import { StyleSheet } from 'react-native';
import { COLORS, FONTS } from '../constants/theme';

export const styles = StyleSheet.create({
  bannerContainer: {
    maxWidth: 1142,
    height: 380,
    backgroundColor: COLORS.navy,
    borderRadius: 4,
    padding: 28,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    width: '100%',
  },
  bannerInnerBorder: {
    height: '100%',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderRadius: 4,
    overflow: 'hidden',
    flexDirection: 'row',
  },
  bannerLeftContent: {
    flex: 2.2,
    paddingHorizontal: 32,
    justifyContent: 'center',
    gap: 16,
    borderRightWidth: 1,
    borderRightColor: 'rgba(255, 255, 255, 0.25)',
    borderBottomColor: 'rgba(255, 255, 255, 0.25)',
  },
  bannerTitle: {
    marginBottom: '24px',
    fontFamily: FONTS.serif,
    fontSize: 24,
    lineHeight: '125%',
    fontWeight: '600',
    color: COLORS.white,
  },
  bannerDescription: {
    maxWidth: 503,
    fontFamily: FONTS.sansSerif,
    fontSize: 18,
    lineHeight: '145%',
    color: COLORS.white,
    fontWeight: '400',
  },
  bannerActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    marginTop: 58,
    flexWrap: 'wrap',
  },
  bannerBtn: {
    height: 48,
    minWidth: 205,
    backgroundColor: COLORS.white,
    // paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bannerBtnText: {
    color: COLORS.textDark,
    fontFamily: FONTS.sansSerif,
    lineHeight: '124%',
    fontWeight: '500',
    fontSize: 16,
    textAlign: 'center',
  },
  bannerIcon: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
  },
  bannerLimitText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 13,
    color: COLORS.textLight,
  },
  stampContainer: {
    flex: 1.1,
    maxWidth: 312,
    maxHeight: 312,
    alignItems: 'center',
    justifyContent: 'center',
    // padding: 16,
  },
  stampImage: {
    width: 384,
    height: 384 ,
    resizeMode: 'fill',
  },
  mobileBannerContainer: {
    height: 475,
    marginLeft: 0,
    marginRight: '-8%',
    backgroundColor: COLORS.navy,
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 16,
    paddingRight: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    width: 'auto',
  },
  mobileBannerInnerBorder: {
    height: '100%',
    borderWidth: 1,
    borderRightWidth: 0,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    borderTopLeftRadius: 4,
    borderBottomLeftRadius: 4,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
    flexDirection: 'column',
  },
  mobileBannerLeftContent: {
    flex: 1,
    paddingTop: 24,
    paddingBottom: 24,
    paddingLeft: 20,
    paddingRight: 24,
    justifyContent: 'space-between',
    gap: 16,
  },
  mobileBannerTitle: {
    marginBottom: 16,
    fontFamily: FONTS.serif,
    fontSize: 20,
    lineHeight: '125%',
    fontWeight: '600',
    color: COLORS.white,
  },
  mobileBannerDescription: {
    fontFamily: FONTS.sansSerif,
    fontSize: 15,
    lineHeight: '145%',
    color: COLORS.white,
    fontWeight: '400',
  },
  mobileBannerActionRow: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
    marginTop: 16,
  },
  mobileBannerBtn: {
    marginTop: 16,
    height: 48,
    minWidth: 205,
    backgroundColor: COLORS.white,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
    borderRadius: 4,
  },
  mobileBannerBtnText: {
    color: COLORS.textDark,
    fontFamily: FONTS.sansSerif,
    lineHeight: '124%',
    fontWeight: '500',
    fontSize: 16,
    textAlign: 'center',
  },
  mobileBannerIcon: {
    width: 14,
    height: 14,
    resizeMode: 'contain',
  },
  mobileBannerLimitText: {
    fontFamily: FONTS.sansSerif,
    fontSize: 14,
    color: COLORS.textLight,
    lineHeight: '125%',
    fontWeight: '400',
    alignSelf: 'center',
    marginTop: 4,
  },
});
