import React, { useEffect, useRef, useState } from 'react';
import { View, Text, TouchableOpacity, Image, useWindowDimensions, Animated, Platform, ScrollView, Linking } from 'react-native';
import { styles } from '../styles/Costs.styles';

const TRIPADVISOR_URL = 'https://www.tripadvisor.com/Hotel_Review-g15019690-d6959182-Reviews-Casa_Romana-Moigrad_Porolissum_Salaj_County_Northwest_Romania_Transylvania.html';

// Walks up the DOM tree to locate the actual scrolling container generated by the React Native ScrollView
function findScrollParent(node) {
  let parent = node && node.parentElement;
  while (parent) {
    const style = window.getComputedStyle(parent);
    const overflowY = style.overflowY;
    const canScroll = (overflowY === 'auto' || overflowY === 'scroll' || overflowY === 'overlay');
    if (canScroll && parent.scrollHeight > parent.clientHeight) {
      return parent;
    }
    parent = parent.parentElement;
  }
  return window;
}

// Cross-platform helper to adjust optical spacing for the digit "1" in Old Standard TT
const KernedPrice = ({ value, style }) => {
  if (typeof value === 'string' && value.startsWith('1')) {
    return (
      <Text style={style}>
        <Text style={{ letterSpacing: -10 }}>1</Text>
        <Text>{value.slice(1)}</Text>
      </Text>
    );
  }
  return <Text style={style}>{value}</Text>;
};

export default function Costs({ onOpenRegister }) {
  const { width } = useWindowDimensions();
  const isDesktop = width >= 900;

  const containerRef = useRef(null);
  const extraTransitionMarkerRef = useRef(null);

  // Carousel scrolling refs and tracking
  const accommodationScrollRef = useRef(null);
  const gunScrollRef = useRef(null);
  const accommodationX = useRef(0);
  const gunX = useRef(0);

  const handleScrollAccommodation = (event) => {
    accommodationX.current = event.nativeEvent.contentOffset.x;
  };

  const handleScrollGun = (event) => {
    gunX.current = event.nativeEvent.contentOffset.x;
  };

  const scrollRef = (ref, currentX, direction) => {
    if (ref.current) {
      const step = 296; // 280 width + 16 gap
      const targetX = direction === 'left' ? Math.max(0, currentX.current - step) : currentX.current + step;
      ref.current.scrollTo({ x: targetX, animated: true });
    }
  };

  const [stickyText, setStickyText] = useState({ first: 'Course', second: 'Cost' });
  const fadeAnim = useRef(new Animated.Value(1)).current;
  const slideAnim = useRef(new Animated.Value(0)).current;

  const viewModeRef = useRef('Course');

  const triggerTextChange = (newText) => {
    viewModeRef.current = newText;
    const useNativeDriver = Platform.OS !== 'web';

    // Smooth slide and fade-out animation sequence
    Animated.parallel([
      Animated.timing(fadeAnim, { toValue: 0, duration: 120, useNativeDriver }),
      Animated.timing(slideAnim, { toValue: -8, duration: 120, useNativeDriver })
    ]).start(() => {
      setStickyText(
        newText === 'Extra'
          ? { first: 'Extra', second: 'Costs' }
          : { first: 'Course', second: 'Cost' }
      );
      Animated.parallel([
        Animated.timing(fadeAnim, { toValue: 1, duration: 180, useNativeDriver }),
        Animated.timing(slideAnim, { toValue: 0, duration: 180, useNativeDriver })
      ]).start();
    });
  };

  // Track scroll position of extras relative to the active viewport
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const el = containerRef.current;
    if (!el) return;

    const scrollParent = findScrollParent(el);
    const isWindow = scrollParent === window;

    let ticking = false;

    const handleScroll = () => {
      if (!ticking) {
        requestAnimationFrame(() => {
          ticking = false;
          const marker = extraTransitionMarkerRef.current;
          if (!marker) return;

          const rect = marker.getBoundingClientRect();

          if (rect.top < 300) {
            if (viewModeRef.current !== 'Extra') {
              triggerTextChange('Extra');
            }
          } else {
            if (viewModeRef.current !== 'Course') {
              triggerTextChange('Course');
            }
          }
        });
        ticking = true;
      }
    };

    handleScroll();

    const scrollTarget = isWindow ? window : scrollParent;
    scrollTarget.addEventListener('scroll', handleScroll, { passive: true });

    return () => {
      scrollTarget.removeEventListener('scroll', handleScroll);
    };
  }, []);

  if (!isDesktop) {
    return (
      <View
        ref={containerRef}
        style={styles.mobileSectionContainer}
      >
        {/* Continuous Left Border Line */}
        <View style={styles.mobileVerticalBorder} />

        <View style={styles.mobileInnerContainer}>
          {/* Mobile: Sticky animated title */}
          <View style={styles.mobileStickyTitleWrapper}>
            <Animated.View style={{ opacity: fadeAnim, transform: [{ translateY: slideAnim }] }}>
              <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                <Text style={styles.mobileStickyTitleFirst}>{stickyText.first} </Text>
                <Text style={styles.mobileStickyTitleSecond}>{stickyText.second}</Text>
              </View>
            </Animated.View>
          </View>

          {/* SECTION 1: Course Cost */}
          <View style={styles.mobileSectionBlock}>
            <KernedPrice value="420eur" style={styles.mobilePriceBig} />
            <Text style={styles.mobileDescTitle}>3 days, 30 hours of active training:</Text>
            <Text style={styles.mobileDescDetail}>includes lunch, dinner, and guided tour</Text>

            <View style={styles.mobileRowDivider} />

            <Text style={styles.mobileNoteLabel}>Important note:</Text>
            <Text style={styles.mobileNoteText}>
              Please note this course is offered at a heavily discounted price to support the development of practical shooting in Romania, and to make it accessible to more shooters.
            </Text>

            <View style={styles.mobileActionRow}>
              <TouchableOpacity style={styles.mobileRegisterBtn} onPress={onOpenRegister}>
                <Text style={styles.mobileRegisterBtnText}>REGISTER NOW</Text>
                <Image source={require('../../assets/images/finger-pad-white.svg')} style={styles.mobileRegisterIcon} />
              </TouchableOpacity>
              <Text style={styles.mobilePlacesLeftText}>Places left: 10</Text>
            </View>
          </View>

          {/* Scroll anchor to detect when we reach the Extra sections */}
          <View
            ref={extraTransitionMarkerRef}
            style={{ height: 1 }}
          />

          {/* SECTION 2: Accommodation */}
          <View style={styles.mobileSectionBlock}>
            <View style={styles.mobileTagRowContainer}>
              <View style={styles.mobileTagWrapper}>
                <Text style={styles.mobileTagText}>Accommodation</Text>
              </View>
              <View style={styles.mobileTagSeparatorLine} />
            </View>

            <View style={{ flexDirection: 'row', alignItems: 'baseline', marginBottom: 8 }}>
              <KernedPrice value="50eur" style={styles.mobilePriceBig} />
              <Text style={styles.mobilePriceUnit}> per night</Text>
            </View>
            <Text style={styles.mobileDescTitle}>*recommended, but you can accommodate wherever you want</Text>

            <View style={styles.mobileRowDivider} />

            <Text style={styles.mobileNoteLabel}>Important note:</Text>
            <Text style={styles.mobileNoteText}>
              Double room with king sized bed (10 rooms available near-site)
            </Text>

            {/* Carousel Block */}
            <View style={styles.mobileCarouselContainer}>
              <ScrollView
                ref={accommodationScrollRef}
                horizontal
                showsHorizontalScrollIndicator={false}
                contentContainerStyle={styles.mobileCarouselScroll}
                scrollEventThrottle={16}
                onScroll={handleScrollAccommodation}
              >
                <Image source={require('../../assets/images/accomodation/hotel-casa-romana.png')} style={styles.mobileCarouselImage} />
                <Image source={require('../../assets/images/accomodation/hotel-casa-romana2.png')} style={styles.mobileCarouselImage} />
                <Image source={require('../../assets/images/accomodation/hotel-casa-romana3.jpg')} style={styles.mobileCarouselImage} />
                <Image source={require('../../assets/images/accomodation/hotel-casa-romana4.jpg')} style={styles.mobileCarouselImage} />
                <Image source={require('../../assets/images/accomodation/hotel-casa-romana5.jpg')} style={styles.mobileCarouselImage} />
                <Image source={require('../../assets/images/accomodation/hotel-casa-romana6.jpg')} style={styles.mobileCarouselImage} />
              </ScrollView>
            </View>

            {/* Link label below carousel */}
            <View style={styles.mobileLinkWrapper}>
              <TouchableOpacity onPress={() => Linking.openURL(TRIPADVISOR_URL)} style={{ flexDirection: 'row', alignItems: 'center' }}>
                <Text style={styles.mobileLinkLabel}>See Accommodation</Text>
                <Image 
                  source={require('../../assets/images/arrow-top-right-corner.svg')} 
                  style={styles.mobileLinkArrow} 
                />
              </TouchableOpacity>
            </View>
          </View>

          {/* SECTION 3: Gun rental and ammo */}
          <View style={styles.mobileSectionBlock}>
            <View style={styles.mobileTagRowContainer}>
              <View style={styles.mobileTagWrapper}>
                <Text style={styles.mobileTagText}>Gun rental and ammo</Text>
              </View>
              <View style={styles.mobileTagSeparatorLine} />
            </View>

            <KernedPrice value="190eur" style={styles.mobilePriceBig} />
            <Text style={styles.mobileDescTitle}>glock 17/19 Gen 5, rig (belt, holster, mag pouches), ear and eye protection</Text>

            <View style={styles.mobileRowDivider} />

            <Text style={styles.mobileNoteLabel}>Important note:</Text>
            <Text style={styles.mobileNoteText}>
              Ammo is calculated for 350 rounds (minimum required for the course). Price details: 90eur gun + rig rental + 100eur ammo (0.28eur/round).
            </Text>

            {/* Carousel Block */}
            <View style={styles.mobileCarouselContainer}>
              <ScrollView
                ref={gunScrollRef}
                horizontal
                showsHorizontalScrollIndicator={false}
                contentContainerStyle={styles.mobileCarouselScroll}
                scrollEventThrottle={16}
                onScroll={handleScrollGun}
              >
                <Image source={require('../../assets/images/equipment/canik-rival-s.jpg')} style={styles.mobileCarouselImage} />
                <Image source={require('../../assets/images/equipment/cz-75-compact.jpg')} style={styles.mobileCarouselImage} />
                <Image source={require('../../assets/images/equipment/cz-75.jpg')} style={styles.mobileCarouselImage} />
                <Image source={require('../../assets/images/equipment/glock-19.jpg')} style={styles.mobileCarouselImage} />
                <Image source={require('../../assets/images/equipment/hk-usp.jpg')} style={styles.mobileCarouselImage} />
              </ScrollView>
            </View>
          </View>
        </View>
      </View>
    );
  }

  return (
    <View
      ref={containerRef}
      style={[styles.sectionContainer, { flexDirection: isDesktop ? 'row' : 'column' }]}
    >
      {/* Sticky Left Column (Desktop Only) */}
      {isDesktop && (
        <View style={styles.leftColumn}>
          <View style={styles.stickyWrapper}>
            <Animated.View style={{ opacity: fadeAnim, transform: [{ translateY: slideAnim }] }}>
              <Text style={styles.sidebarFirstWord}>{stickyText.first}</Text>
              <Text style={styles.sidebarSecondWord}>{stickyText.second}</Text>
            </Animated.View>
          </View>
        </View>
      )}

      {/* Main Breakdown Column (Right Side) */}
      <View style={[styles.mainColumn, { paddingLeft: isDesktop ? 40 : 0 }]}>

        {/* Mobile: Sticky animated title (replaces left column) */}
        {!isDesktop && (
          <View style={styles.mobileStickyTitleWrapper}>
            <Animated.View style={{ opacity: fadeAnim, transform: [{ translateY: slideAnim }] }}>
              <Text style={styles.mobileStickyTitleFirst}>{stickyText.first}</Text>
              <Text style={styles.mobileStickyTitleSecond}>{stickyText.second}</Text>
            </Animated.View>
          </View>
        )}

        {/* SECTION 1: Course Cost */}
        <View style={styles.sectionBlock}>
          <View style={styles.gridRow}>
            <View style={styles.gridLeft}>
              <KernedPrice value="420eur" style={styles.priceBig} />
            </View>
            <View style={styles.gridRight}>
              <Text style={styles.descTitle}>3 days, 30 hours of active training:</Text>
              <Text style={styles.descDetail}>includes lunch, dinner, and guided tour</Text>
            </View>
          </View>

          <View style={styles.rowDivider} />

          <View style={styles.gridRow}>
            <View style={styles.gridLeft}>
              <Text style={styles.noteLabel}>Important note:</Text>
            </View>
            <View style={styles.gridRight}>
              <Text style={styles.noteText}>
                Please note this course is offered at a heavily discounted price to support the development of practical shooting in Romania, and to make it accessible to more shooters.
              </Text>
            </View>
          </View>

          <View style={styles.actionRow}>
            <TouchableOpacity style={styles.registerBtn} onPress={onOpenRegister}>
              <Text style={styles.registerBtnText}>REGISTER NOW</Text>
              <Image source={require('../../assets/images/finger-pad-white.svg')} style={styles.registerIcon} />
            </TouchableOpacity>
            <Text style={styles.placesLeftText}>Places left: 10</Text>
          </View>
        </View>

        {/* Scroll anchor to detect when we reach the Extra sections */}
        <View
          ref={extraTransitionMarkerRef}
          style={{ height: 1 }}
        />

        {/* SECTION 2: Accommodation */}
        <View style={styles.sectionBlock}>
          <View style={styles.tagRowContainer}>
            <View style={styles.tagWrapper}>
              <Text style={styles.tagText}>Accommodation</Text>
            </View>
            <View style={styles.tagSeparatorLine} />
          </View>

          <View style={styles.gridRow}>
            <View style={styles.gridLeft}>
              <View style={{ flexDirection: 'row', alignItems: 'baseline' }}>
                <KernedPrice value="50eur" style={styles.priceBig} />
                <Text style={styles.priceUnit}> per night</Text>
              </View>
            </View>
            <View style={styles.gridRight}>
              <Text style={styles.descTitle}>*recommended, but not required, you can accommodate wherever you want</Text>
            </View>
          </View>

          <View style={styles.rowDivider} />

          <View style={styles.gridRow}>
            <View style={styles.gridLeft}>
              <Text style={styles.noteLabel}>Important note:</Text>
            </View>
            <View style={styles.gridRight}>
              <Text style={styles.noteText}>
                Double room with king sized bed{"\n"}(10 rooms available near-site)
              </Text>
            </View>
          </View>

          {/* Carousel Block */}
          <View style={styles.carouselContainer}>
            <TouchableOpacity 
              style={[styles.carouselArrow, styles.arrowLeft]} 
              activeOpacity={0.8}
              onPress={() => scrollRef(accommodationScrollRef, accommodationX, 'left')}
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none" style={{ transform: 'rotate(180deg)' }}>
                <g clipPath="url(#clip0_300_411)">
                  <path d="M0.5625 9H17.4375" stroke="#091413" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                  <path d="M9.5625 16.875L17.4375 9L9.5625 1.125" stroke="#091413" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                </g>
                <defs>
                  <clipPath id="clip0_300_411">
                    <rect width="18" height="18" fill="white"/>
                  </clipPath>
                </defs>
              </svg>
            </TouchableOpacity>

            <ScrollView
              ref={accommodationScrollRef}
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={styles.carouselScroll}
              scrollEventThrottle={16}
              onScroll={handleScrollAccommodation}
            >
              <Image source={require('../../assets/images/accomodation/hotel-casa-romana.png')} style={styles.carouselImage} />
              <Image source={require('../../assets/images/accomodation/hotel-casa-romana2.png')} style={styles.carouselImage} />
              <Image source={require('../../assets/images/accomodation/hotel-casa-romana3.jpg')} style={styles.carouselImage} />
              <Image source={require('../../assets/images/accomodation/hotel-casa-romana4.jpg')} style={styles.carouselImage} />
              <Image source={require('../../assets/images/accomodation/hotel-casa-romana5.jpg')} style={styles.carouselImage} />
              <Image source={require('../../assets/images/accomodation/hotel-casa-romana6.jpg')} style={styles.carouselImage} />
            </ScrollView>

            <TouchableOpacity 
              style={[styles.carouselArrow, styles.arrowRight]} 
              activeOpacity={0.8}
              onPress={() => scrollRef(accommodationScrollRef, accommodationX, 'right')}
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
                <g clipPath="url(#clip0_300_411)">
                  <path d="M0.5625 9H17.4375" stroke="#091413" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                  <path d="M9.5625 16.875L17.4375 9L9.5625 1.125" stroke="#091413" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                </g>
                <defs>
                  <clipPath id="clip0_300_411">
                    <rect width="18" height="18" fill="white"/>
                  </clipPath>
                </defs>
              </svg>
            </TouchableOpacity>
          </View>

          {/* Link label below carousel */}
          <View style={styles.linkWrapper}>
            <TouchableOpacity onPress={() => Linking.openURL(TRIPADVISOR_URL)} style={{ flexDirection: 'row', alignItems: 'center' }}>
              <Text style={styles.linkLabel}>See Accommodation</Text>
              <Image 
                source={require('../../assets/images/arrow-top-right-corner.svg')} 
                style={styles.linkArrow} 
              />
            </TouchableOpacity>
          </View>
        </View>

        {/* SECTION 3: Gun rental and ammo */}
        <View style={styles.sectionBlock}>
          <View style={styles.tagRowContainer}>
            <View style={styles.tagWrapper}>
              <Text style={styles.tagText}>Gun rental and ammo</Text>
            </View>
            <View style={styles.tagSeparatorLine} />
          </View>

          <View style={styles.gridRow}>
            <View style={styles.gridLeft}>
              <KernedPrice value="190eur" style={styles.priceBig} />
            </View>
            <View style={styles.gridRight}>
              <Text style={[styles.descTitle]}>
                *recommended, but you can accommodate wherever you want
              </Text>
            </View>
          </View>

          <View style={styles.rowDivider} />

          <View style={styles.gridRow}>
            <View style={styles.gridLeft}>
              <Text style={styles.noteLabel}>Important note:</Text>
            </View>
            <View style={styles.gridRight}>
              <Text style={styles.noteText}>
                Includes gun, belt, pouches, holster, eyes & ear protection + 350 rounds
              </Text>
            </View>
          </View>

          {/* Carousel Block */}
          <View style={styles.carouselContainer}>
            <TouchableOpacity 
              style={[styles.carouselArrow, styles.arrowLeft]} 
              activeOpacity={0.8}
              onPress={() => scrollRef(gunScrollRef, gunX, 'left')}
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none" style={{ transform: 'rotate(180deg)' }}>
                <g clipPath="url(#clip0_300_411)">
                  <path d="M0.5625 9H17.4375" stroke="#091413" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                  <path d="M9.5625 16.875L17.4375 9L9.5625 1.125" stroke="#091413" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                </g>
                <defs>
                  <clipPath id="clip0_300_411">
                    <rect width="18" height="18" fill="white"/>
                  </clipPath>
                </defs>
              </svg>
            </TouchableOpacity>

            <ScrollView
              ref={gunScrollRef}
              horizontal
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={styles.carouselScroll}
              scrollEventThrottle={16}
              onScroll={handleScrollGun}
            >
              <Image source={require('../../assets/images/equipment/canik-rival-s.jpg')} style={styles.carouselImage} />
              <Image source={require('../../assets/images/equipment/cz-75-compact.jpg')} style={styles.carouselImage} />
              <Image source={require('../../assets/images/equipment/cz-75.jpg')} style={styles.carouselImage} />
              <Image source={require('../../assets/images/equipment/glock-19.jpg')} style={styles.carouselImage} />
              <Image source={require('../../assets/images/equipment/hk-usp.jpg')} style={styles.carouselImage} />
            </ScrollView>

            <TouchableOpacity 
              style={[styles.carouselArrow, styles.arrowRight]} 
              activeOpacity={0.8}
              onPress={() => scrollRef(gunScrollRef, gunX, 'right')}
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
                <g clipPath="url(#clip0_300_411)">
                  <path d="M0.5625 9H17.4375" stroke="#091413" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                  <path d="M9.5625 16.875L17.4375 9L9.5625 1.125" stroke="#091413" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                </g>
                <defs>
                  <clipPath id="clip0_300_411">
                    <rect width="18" height="18" fill="white"/>
                  </clipPath>
                </defs>
              </svg>
            </TouchableOpacity>
          </View>
        </View>

      </View>
    </View>
  );
}
